### ISSUE TITLE
An internal error occured.

### ISSUE THREAD

**Issue by uraqtlee** [HealPot/EnchantmentsEnhance#1]
I get this error when I do /enhance select

[21:47:10 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'enha
nce' in plugin EnchantmentsEnhance v3.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[cra
ftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServ
er.java:648) ~[craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerCo
nnection.java:1397) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.jav
a:1232) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.jav
a:45) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.jav
a:1) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:
13) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukk
it.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:
748) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
406) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
679) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:577) [craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324)
 ~[craftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        at org.pixeltime.healpot.enhancement.util.Util.sendMessage(Util.java:150
) ~[?:?]
        at org.pixeltime.healpot.enhancement.events.blacksmith.SecretBook.select
(SecretBook.java:112) ~[?:?]
        at org.pixeltime.healpot.enhancement.Main.onCommand(Main.java:181) ~[?:?
]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[cra
ftbukkit.jar:git-Spigot-c3093ef-7e94e65]
        ... 15 more

**Comment by HealPot** [comment]
Thank you for reporting the bug! Your issue has been addressed in the recent commit.
